### ISSUE TITLE
Missing Docker compose file?

### ISSUE THREAD

**Issue by UltraHKR** [CorralPeltzer/newTrackon#128]
Would you please provide a docker compose .yml please?

This file is missing the required files and or instructions:
https://github.com/CorralPeltzer/newTrackon/blob/master/Dockerfile

Proposed dockercompose file:
```
--
version: '3.3'
services:
  newtrackon:
    container_name: newtrackon
    ports:
      - 8080:8080
    image: corralpeltzer/newtrackon:latest

   ### If you have full IPv4 & IPv6 use as-is, otherwise add --ignore-ipv4 or --ignore-ipv6 as required:
    command: --address=0.0.0.0
```

**Comment by CorralPeltzer** [comment]
Hi! Looks good, feel free to open a PR, I'll do it in a few days otherwise.

**Comment by UltraHKR** [comment]
Hi, Miguel

Before I do a PR

Can you help me out with the volume path?

**Comment by CorralPeltzer** [comment]
That'd depend on specific needs, but I guess a decent use case could be having a folder with the DB and logs from newTrackon in your home directory:

```
services:
  newtrackon:
    container_name: newtrackon
    ports:
      - 8080:8080
    volumes:
      - ~/newTrackon-data:/app/newTrackon/data
    image: corralpeltzer/newtrackon:latest

    ### If you have full IPv4 & IPv6 use as-is, otherwise add --ignore-ipv4 or --ignore-ipv6 as required:
    command: --address=0.0.0.0
```
